
from setuptools import setup, Extension
from Cython.Build import cythonize

# SOURCES = [
#     # _xzyre.cpp contains the wrapper created with pybindgen.
#     # It is generated by running:
#     #   pipenv run python xzyre/generate.py
#     'src/aiozyre/xzyre.cpp',
# ]

#
# XZYRE_EXTENSION = dict(
#     sources=SOURCES,
#     libraries=['czmq', 'zyre'],
#     # Uncomment for debug build
#     # extra_compile_args=["-Wall", "-g", "-O0"]
# )

setup(
    name='aiozyre',
    version='0.1.0',
    description='asyncio-friendly Python bindings for Zyre',
    author='Elijah Shaw-Rutschman',
    author_email='elijahr+aiozyre@gmail.com',
    packages=['aiozyre'],
    package_dir={'': 'src'},
    ext_modules=[
        # Extension(
        #     'aiozyre.xzyre',
        #     **XZYRE_EXTENSION
        # )
    ] + cythonize([
        Extension('zyrex', ['zyrex.pyx'], libraries=['czmq', 'zyre']),
        Extension('zyrex_util', ['zyrex_util.pyx'], libraries=['czmq', 'zyre']),
        Extension('zyrex_msg', ['zyrex_msg.pyx'], libraries=['czmq', 'zyre']),
    ]),
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: MacOS :: MacOS X',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3',
        'Topic :: System :: Networking',
        'Framework :: AsyncIO',
    ],
)
