# cython: language_level=3

cdef enum SIGNALS:
    SHOUT, WHISPER, JOIN, LEAVE, PEERS, PEERS_BY_GROUP, OWN_GROUPS, PEER_GROUPS, PEER_ADDRESS, PEER_HEADER_VALUE, \
    STOP

cdef char* TERM
cdef char * INCOMING